### ISSUE TITLE
Plugin icon is displayed larger

### ISSUE THREAD

**Issue by sin-tanaka** [thinkAmi/railroads#46]
Hello. I am using your plugin conveniently.

I found a behavior that may be a bug and I would like to report it.

---

## Version

Railroads: 0.2.0
IntelliJ: IntelliJ IDEA 2024.1.4 (Ultimate Edition) Build #IU-241.18034.62, built on June 21, 2024

## Problem

Plugin icon is displayed larger and the sidebar is wider.

![スクリーンショット 2024-09-02 11 55 56](https://github.com/user-attachments/assets/52cfcf19-e061-424e-8cb2-70be5b89168f)

I manually downgraded to version 0.1.1 and it is back to normal.

![スクリーンショット 2024-09-02 12 10 46](https://github.com/user-attachments/assets/072d831a-4ae8-4f28-b51b-192b612b65eb)

**Comment by thinkAmi** [comment]
Thank you for the bug report.
Also, thank you for providing the version of the IDE or plugin where the bug occurred and the screenshot from when it happened.

Now, I will proceed with checking and addressing the issue, so please allow me some time.

The main difference between versions 0.1.1 and 0.2.0 is the icons, so if you are concerned, please downgrade to 0.1.1.

**Comment by thinkAmi** [comment]
The icon size was corrected in PR #47 
I have also released the corrected plugin as 0.2.1.

So, it would be helpful if you could install the plugin version 0.2.1 and check its operation.

**Comment by sin-tanaka** [comment]
I have confirmed that it has been fixed.

Thank you for fixing the problem so quickly!
